#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : libsolv
Version  : 0.7.19
Release  : 26
URL      : file:///aot/build/clearlinux/packages/libsolv/libsolv-0.7.19.tar.gz
Source0  : file:///aot/build/clearlinux/packages/libsolv/libsolv-0.7.19.tar.gz
Summary  : Library for solving packages
Group    : Development/Tools
License  : GPL-2.0
Requires: libsolv-bin = %{version}-%{release}
Requires: libsolv-data = %{version}-%{release}
Requires: libsolv-lib = %{version}-%{release}
Requires: libsolv-man = %{version}-%{release}
BuildRequires : Sphinx
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : bzip2-dev
BuildRequires : bzip2-staticdev
BuildRequires : check-dev
BuildRequires : doxygen
BuildRequires : expat-dev
BuildRequires : expat-staticdev
BuildRequires : libxml2-dev
BuildRequires : libxml2-staticdev
BuildRequires : lz4-dev
BuildRequires : lz4-staticdev
BuildRequires : lzo-dev
BuildRequires : lzo-staticdev
BuildRequires : pkg-config
BuildRequires : pkgconfig(expat)
BuildRequires : pkgconfig(liblzma)
BuildRequires : pkgconfig(rpm)
BuildRequires : popt-dev
BuildRequires : python3-dev
BuildRequires : python3-staticdev
BuildRequires : xz-dev
BuildRequires : xz-staticdev
BuildRequires : zlib
BuildRequires : zlib-dev
BuildRequires : zlib-staticdev
BuildRequires : zstd-dev
BuildRequires : zstd-staticdev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Libsolv
=======
This is libsolv, a free package dependency solver using a satisfiability
algorithm.

%package bin
Summary: bin components for the libsolv package.
Group: Binaries
Requires: libsolv-data = %{version}-%{release}

%description bin
bin components for the libsolv package.


%package data
Summary: data components for the libsolv package.
Group: Data

%description data
data components for the libsolv package.


%package dev
Summary: dev components for the libsolv package.
Group: Development
Requires: libsolv-lib = %{version}-%{release}
Requires: libsolv-bin = %{version}-%{release}
Requires: libsolv-data = %{version}-%{release}
Provides: libsolv-devel = %{version}-%{release}
Requires: libsolv = %{version}-%{release}

%description dev
dev components for the libsolv package.


%package lib
Summary: lib components for the libsolv package.
Group: Libraries
Requires: libsolv-data = %{version}-%{release}

%description lib
lib components for the libsolv package.


%package man
Summary: man components for the libsolv package.
Group: Default

%description man
man components for the libsolv package.


%package staticdev
Summary: staticdev components for the libsolv package.
Group: Default
Requires: libsolv-dev = %{version}-%{release}

%description staticdev
staticdev components for the libsolv package.


%prep
%setup -q -n libsolv
cd %{_builddir}/libsolv

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1618909594
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
## altflags_pgo content
## pgo generate
export PGO_GEN="-fprofile-generate=/var/tmp/pgo -fprofile-dir=/var/tmp/pgo -fprofile-abs-path -fprofile-update=atomic -fprofile-arcs -ftest-coverage --coverage -fprofile-partial-training"
export CFLAGS_GENERATE="-O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -falign-functions=32 -flimit-function-alignment -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe -ffat-lto-objects -flto=16 -fPIC -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc $PGO_GEN"
export FCFLAGS_GENERATE="-O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -falign-functions=32 -flimit-function-alignment -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe -ffat-lto-objects -flto=16 -fPIC -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc $PGO_GEN"
export FFLAGS_GENERATE="-O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -falign-functions=32 -flimit-function-alignment -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe -ffat-lto-objects -flto=16 -fPIC -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc $PGO_GEN"
export CXXFLAGS_GENERATE="-O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -falign-functions=32 -flimit-function-alignment -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -fvisibility-inlines-hidden -pipe -ffat-lto-objects -flto=16 -fPIC -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc $PGO_GEN"
export LDFLAGS_GENERATE="-O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -falign-functions=32 -flimit-function-alignment -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe -ffat-lto-objects -flto=16 -fPIC -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -lpthread $PGO_GEN"
## pgo use
## -ffat-lto-objects -fno-PIE -fno-PIE -m64 -no-pie -fpic -fvisibility=hidden -flto-partition=none
## gcc: -feliminate-unused-debug-types -fipa-pta -flto=16 -Wno-error -Wp,-D_REENTRANT -fno-common
export PGO_USE="-fprofile-use=/var/tmp/pgo -fprofile-dir=/var/tmp/pgo -fprofile-abs-path -fprofile-correction -fprofile-partial-training"
export CFLAGS_USE="-O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc $PGO_USE"
export FCFLAGS_USE="-O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc $PGO_USE"
export FFLAGS_USE="-O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc $PGO_USE"
export CXXFLAGS_USE="-O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc $PGO_USE"
export LDFLAGS_USE="-O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -lpthread $PGO_USE"
#
export AR=/usr/bin/gcc-ar
export RANLIB=/usr/bin/gcc-ranlib
export NM=/usr/bin/gcc-nm
#
export MAKEFLAGS=%{?_smp_mflags}
#
%global _lto_cflags 1
#global _lto_cflags %{nil}
%global _disable_maintainer_mode 1
#%global _disable_maintainer_mode %{nil}
#
export CCACHE_DISABLE=true
export PATH="/usr/lib64/ccache/bin:$PATH"
export CCACHE_NOHASHDIR=true
export CCACHE_CPP2=true
export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,file_stat_matches,file_stat_matches_ctime,include_file_ctime,include_file_mtime,modules,system_headers,clang_index_store,file_macro
#export CCACHE_SLOPPINESS=modules,include_file_mtime,include_file_ctime,time_macros,pch_defines,file_stat_matches,clang_index_store,system_headers,locale
#export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,clang_index_store,file_macro
export CCACHE_DIR=/var/tmp/ccache
export CCACHE_BASEDIR=/builddir/build/BUILD
#export CCACHE_LOGFILE=/var/tmp/ccache/cache.debug
#export CCACHE_DEBUG=true
#export CCACHE_NODIRECT=true
## altflags_pgo end
if [ ! -f statuspgo ]; then
echo PGO Phase 1
export CFLAGS="${CFLAGS_GENERATE}"
export CXXFLAGS="${CXXFLAGS_GENERATE}"
export FFLAGS="${FFLAGS_GENERATE}"
export FCFLAGS="${FCFLAGS_GENERATE}"
export LDFLAGS="${LDFLAGS_GENERATE}"
%cmake .. -DENABLE_COMPLEX_DEPS=YES \
-DENABLE_RPMDB=YES \
-DENABLE_RPMDB_BYRPMHEADER=YES \
-DENABLE_RPMDB_LIBRPM=YES \
-DENABLE_RPMPKG_LIBRPM=YES \
-DENABLE_RPMMD=YES \
-DENABLE_LZMA_COMPRESSION=yes \
-DENABLE_ZCHUNK_COMPRESSION=OFF \
-DENABLE_STATIC=ON \
-DENABLE_LZMA_COMPRESSION=ON \
-DENABLE_BZIP2_COMPRESSION=ON \
-DENABLE_ZSTD_COMPRESSION=ON \
-DWITH_LIBXML2=ON
make  %{?_smp_mflags}

ctest --parallel 16 -V --progress || :
make -j1 check || :
make -j1 test  || :
find . -type f,l -not -name '*.gcno' -not -name 'statuspgo*' -delete -print
echo USED > statuspgo
fi
if [ -f statuspgo ]; then
echo PGO Phase 2
export CFLAGS="${CFLAGS_USE}"
export CXXFLAGS="${CXXFLAGS_USE}"
export FFLAGS="${FFLAGS_USE}"
export FCFLAGS="${FCFLAGS_USE}"
export LDFLAGS="${LDFLAGS_USE}"
%cmake .. -DENABLE_COMPLEX_DEPS=YES \
-DENABLE_RPMDB=YES \
-DENABLE_RPMDB_BYRPMHEADER=YES \
-DENABLE_RPMDB_LIBRPM=YES \
-DENABLE_RPMPKG_LIBRPM=YES \
-DENABLE_RPMMD=YES \
-DENABLE_LZMA_COMPRESSION=yes \
-DENABLE_ZCHUNK_COMPRESSION=OFF \
-DENABLE_STATIC=ON \
-DENABLE_LZMA_COMPRESSION=ON \
-DENABLE_BZIP2_COMPRESSION=ON \
-DENABLE_ZSTD_COMPRESSION=ON \
-DWITH_LIBXML2=ON
make  %{?_smp_mflags}
fi
popd

%install
export SOURCE_DATE_EPOCH=1618909594
rm -rf %{buildroot}
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/deltainfoxml2solv
/usr/bin/dumpsolv
/usr/bin/installcheck
/usr/bin/mergesolv
/usr/bin/repo2solv
/usr/bin/repomdxml2solv
/usr/bin/rpmdb2solv
/usr/bin/rpmmd2solv
/usr/bin/rpms2solv
/usr/bin/testsolv
/usr/bin/updateinfoxml2solv

%files data
%defattr(-,root,root,-)
/usr/share/cmake/*

%files dev
%defattr(-,root,root,-)
/usr/include/solv/bitmap.h
/usr/include/solv/chksum.h
/usr/include/solv/dataiterator.h
/usr/include/solv/dirpool.h
/usr/include/solv/evr.h
/usr/include/solv/hash.h
/usr/include/solv/knownid.h
/usr/include/solv/policy.h
/usr/include/solv/pool.h
/usr/include/solv/pool_fileconflicts.h
/usr/include/solv/pool_parserpmrichdep.h
/usr/include/solv/poolarch.h
/usr/include/solv/poolid.h
/usr/include/solv/pooltypes.h
/usr/include/solv/poolvendor.h
/usr/include/solv/problems.h
/usr/include/solv/queue.h
/usr/include/solv/repo.h
/usr/include/solv/repo_deltainfoxml.h
/usr/include/solv/repo_repomdxml.h
/usr/include/solv/repo_rpmdb.h
/usr/include/solv/repo_rpmmd.h
/usr/include/solv/repo_solv.h
/usr/include/solv/repo_updateinfoxml.h
/usr/include/solv/repo_write.h
/usr/include/solv/repodata.h
/usr/include/solv/rules.h
/usr/include/solv/selection.h
/usr/include/solv/solv_xfopen.h
/usr/include/solv/solvable.h
/usr/include/solv/solver.h
/usr/include/solv/solverdebug.h
/usr/include/solv/solvversion.h
/usr/include/solv/strpool.h
/usr/include/solv/testcase.h
/usr/include/solv/tools_util.h
/usr/include/solv/transaction.h
/usr/include/solv/util.h
/usr/lib64/libsolv.so
/usr/lib64/libsolvext.so
/usr/lib64/pkgconfig/libsolv.pc
/usr/lib64/pkgconfig/libsolvext.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libsolv.so.1
/usr/lib64/libsolvext.so.1

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/deltainfoxml2solv.1
/usr/share/man/man1/dumpsolv.1
/usr/share/man/man1/installcheck.1
/usr/share/man/man1/mergesolv.1
/usr/share/man/man1/repo2solv.1
/usr/share/man/man1/repomdxml2solv.1
/usr/share/man/man1/rpmdb2solv.1
/usr/share/man/man1/rpmmd2solv.1
/usr/share/man/man1/rpms2solv.1
/usr/share/man/man1/solv.1
/usr/share/man/man1/testsolv.1
/usr/share/man/man1/updateinfoxml2solv.1
/usr/share/man/man3/libsolv-bindings.3
/usr/share/man/man3/libsolv-constantids.3
/usr/share/man/man3/libsolv-history.3
/usr/share/man/man3/libsolv-pool.3
/usr/share/man/man3/libsolv.3

%files staticdev
%defattr(-,root,root,-)
/usr/lib64/libsolv.a
/usr/lib64/libsolvext.a
